# Research Paper Search and Summarization

In [125]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

## 1. Data Loading and Preprocessing

In [126]:
from datasets import load_dataset

In [127]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')

In [128]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [129]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [130]:
import pandas as pd

In [131]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [132]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [133]:
df=df[['title','abstract']]

In [134]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [135]:
# Reduce the no of rows
df=df.head(15000)
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th..."
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...
14999,On Fairness and Calibration,The machine learning community has become in...

In [136]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [137]:
df["paper_text"]=df["title"]+" "+df["abstract"]
df

/tmp/ipykernel_8364/3936252372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...
14999,On Fairness and Calibration,The machine learning community has become in...,On Fairness and Calibration The machine lear...

In [138]:
# converting into dataframe
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [139]:
type(df[["paper_text"]].head())

pandas.core.frame.DataFrame

In [140]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [141]:
from sentence_transformers import SentenceTransformer

## 2. Generating Sentence Embeddings

In [142]:
# 1. Load a pretrained Sentence Transformer model

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [143]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [144]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [145]:
# Removed \n(new line) so that model does not become confuse with \n
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df

/tmp/ipykernel_8364/1813364570.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...
14999,On Fairness and Calibration,The machine learning community has become in...,On Fairness and Calibration The machine lear...

In [146]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise. '

In [147]:
# Removed white spaces in front and last
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_8364/1640325731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [148]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [149]:
# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sample_text)
print(embeddings.shape)
print(type(embeddings))

(384,)
<class 'numpy.ndarray'>

In [150]:
embeddings

array([-1.31564081e-01, -6.78268261e-03, -3.67608899e-03,  3.26516181e-02,
        1.12196378e-01,  1.22726625e-02,  9.81672332e-02, -9.00522768e-02,
        4.23116535e-02, -1.97735038e-02, -3.30841728e-02,  7.45293945e-02,
        1.06320381e-01, -2.06043050e-02, -2.05210242e-02,  1.69492350e-03,
        7.08194748e-02,  5.85444868e-02, -1.12319104e-01,  2.08246931e-02,
        5.69254532e-02,  2.01578029e-02,  2.58310027e-02,  3.21702920e-02,
        1.05137683e-01, -9.67675969e-02,  2.70080213e-02, -2.34509017e-02,
       -4.54967879e-02, -1.01369787e-02, -1.79485511e-02, -4.81442735e-02,
        1.07765254e-02, -3.75906937e-02,  1.94347762e-02,  3.71518992e-02,
        2.96784285e-02,  4.33094352e-02,  4.37320806e-02,  3.70486639e-02,
       -1.82593311e-03,  4.55186190e-03, -7.99066573e-03,  3.03737260e-02,
       -1.43779982e-02,  3.79514992e-02,  5.95916100e-02, -2.58336067e-02,
       -6.52156994e-02,  5.90026602e-02, -2.10713837e-02,  7.35942796e-02,
       -5.72010837e-02,  2.94060167e-03,  7.67515041e-03, -3.33416462e-02,
       -2.41654906e-02, -2.09911615e-02, -4.76784147e-02,  1.42030016e-01,
       -4.16863412e-02, -2.28165798e-02, -1.45359328e-02, -4.39254567e-03,
       -6.80174530e-02, -2.55161035e-03,  7.34624639e-02,  4.29371335e-02,
       -3.04794516e-02,  5.82108907e-02, -8.45503956e-02, -5.60203753e-03,
       -9.26086307e-02,  5.90392388e-02,  1.99682172e-02, -1.46549502e-02,
        8.56686234e-02,  3.43409888e-02,  4.26304247e-03, -2.55768765e-02,
       -2.92939134e-02,  2.88600149e-03,  3.02558262e-02, -5.09372503e-02,
        3.13304625e-02, -1.24026127e-02,  1.93743743e-02,  7.15281814e-02,
        3.50777842e-02,  4.40818164e-03, -1.08218908e-01, -2.98318528e-02,
       -6.13418780e-02,  4.19662297e-02,  4.72577587e-02, -5.66609912e-02,
        6.82019144e-02, -7.44092762e-02,  9.27867815e-02,  9.60960016e-02,
       -6.80272952e-02,  1.62349700e-03,  4.31858897e-02, -3.07623986e-02,
        1.11808944e-02, -8.54723901e-02,  2.37832796e-02,  1.73624344e-02,
        5.39869443e-03,  1.58846918e-02,  4.44355840e-03, -1.15580782e-02,
       -9.76491999e-03, -7.40200980e-03, -1.88762210e-02, -3.39675508e-02,
       -4.86566983e-02,  4.36527021e-02, -1.04922488e-01, -8.63314867e-02,
       -4.52507883e-02, -7.29720369e-02, -2.08166558e-02,  3.65953967e-02,
       -8.82899854e-03, -2.35993974e-02, -4.47208285e-02,  1.54469049e-33,
        2.61055809e-02,  5.34729399e-02, -3.32894102e-02, -4.06732187e-02,
        2.65870914e-02,  8.22318122e-02, -7.54074007e-03, -1.62798184e-04,
        6.65079877e-02,  4.61812504e-02, -4.74173985e-02, -5.05928211e-02,
       -3.38295214e-02,  4.62175570e-02,  4.43545021e-02,  4.41355109e-02,
       -7.10298568e-02,  7.09742829e-02,  1.83767695e-02, -7.27372840e-02,
        7.00070262e-02, -2.09407751e-02, -5.53729162e-02, -4.75662984e-02,
       -4.31161672e-02, -5.32935895e-02,  2.69028824e-04, -3.83734964e-02,
        1.12205390e-02,  1.13959024e-02, -5.69416136e-02, -3.37936450e-03,
        1.03546835e-01, -8.47086832e-02,  3.53652635e-03, -5.72201125e-02,
        1.27505083e-02, -5.53160114e-03, -8.56065676e-02,  3.96664143e-02,
        2.25463845e-02,  4.99202050e-02,  4.13550735e-02, -2.60567181e-02,
       -5.83662540e-02, -7.51372203e-02,  1.08070470e-01,  6.15525758e-04,
       -9.01391432e-02, -1.32652476e-01, -2.54445756e-03, -3.37497741e-02,
       -9.57633257e-02,  2.57490261e-04,  1.16858864e-02,  2.23589875e-02,
        4.88692932e-02, -4.24660258e-02, -2.45967675e-02,  8.56855437e-02,
       -8.03445056e-02,  3.33040915e-02,  5.40195294e-02, -3.71836126e-02,
        2.11858453e-04,  1.86595935e-02,  3.10018063e-02, -5.36219701e-02,
        5.17720878e-02, -1.01843201e-01,  3.34464721e-02, -4.58089914e-03,
       -2.21982431e-02, -5.00103049e-02,  3.52233127e-02,  1.97153073e-02,
        1.44824944e-02, -6.63911970e-03, -1.26853110e-02, -1.63103209e-03,
       -4.83979322e-02, -4.59996164e-02, -1.93057302e-02, -2.97057275e-02,
       -5.00632413e-02,  3.04493252e-02,  1.81869511e-02, -4.53428403e-02,
       -4.88783717e-02,  1.22215669e-03, -1.06096081e-01, -3.71801034e-02,
       -7.55688772e-02, -4.81151938e-02,  2.25063693e-02, -2.23424466e-33,
       -2.21984442e-02,  8.51170868e-02,  2.62743942e-02,  5.43512963e-02,
       -1.57290511e-02, -1.96615271e-02, -2.73119435e-02,  2.96456143e-02,
       -4.53335932e-03, -8.33163485e-02, -9.22681540e-02, -4.08937410e-02,
        7.32074529e-02,  4.30881269e-02, -7.74768442e-02,  7.20389485e-02,
       -1.40663767e-02,  4.46009338e-02, -4.19448242e-02,  3.33845168e-02,
        2.91045308e-02,  3.20830084e-02,  2.09529139e-02,  2.23059356e-02,
        4.44135740e-02,  2.03914437e-02, -5.60237691e-02,  1.84909612e-01,
        2.28254627e-02, -7.39143044e-03, -4.18754481e-02, -7.15967044e-02,
       -6.42080680e-02, -6.63447976e-02, -2.05955002e-02,  1.06428675e-02,
        5.02160098e-03,  6.77870363e-02, -7.12078810e-02,  1.02496579e-01,
        9.44259092e-02,  3.30481716e-02, -5.00413291e-02,  2.62114871e-02,
        5.58213592e-02, -6.59461617e-02,  1.79096721e-02, -1.04770111e-02,
        7.34620616e-02, -2.46886699e-03,  3.85357961e-02,  4.46167924e-02,
       -2.85524111e-02,  9.08054188e-02, -7.84087647e-03, -2.77606212e-03,
       -9.57009941e-02, -1.16200140e-02,  5.25497869e-02,  9.29363817e-02,
       -6.14787592e-03,  8.09927005e-03, -6.72860369e-02,  8.18502828e-02,
        3.28586693e-03, -3.50580998e-02, -1.84767544e-02, -8.98877697e-05,
        7.32783079e-02,  9.57325473e-02,  4.15686294e-02, -6.18869103e-02,
        2.83940379e-02,  4.25409973e-02,  1.89858377e-02,  1.06750615e-02,
        2.51713470e-02,  3.08217891e-02, -6.59718364e-02,  8.87987316e-02,
        3.82416993e-02,  9.21778753e-02,  5.19544557e-02,  2.64020055e-03,
        1.49983610e-03,  5.44707179e-02,  7.31122494e-02, -8.08765879e-04,
        7.52013847e-02, -1.16245136e-01,  1.17986342e-02,  6.28149882e-02,
       -3.60431038e-02,  2.93700509e-02, -1.52512547e-02, -4.79335256e-08,
       -5.37610017e-02, -2.84531713e-02,  2.40290482e-02, -7.81880319e-02,
        1.01736061e-01, -2.52304040e-02,  7.01657124e-03, -2.86819041e-03,
        2.01843977e-02, -3.77830639e-02,  7.34866560e-02, -1.10322016e-03,
       -7.07775950e-02, -4.50034887e-02, -2.81599276e-02,  1.05185434e-02,
       -3.94661305e-03,  3.17634530e-02,  2.70489678e-02,  2.42667142e-02,
        3.24968994e-02, -2.10961681e-02, -5.78851253e-03, -2.25947089e-02,
        2.25188285e-02, -6.81575835e-02,  3.87890302e-02, -2.75328327e-02,
        1.55410431e-02,  1.14076234e-01, -5.39854839e-02,  3.54755819e-02,
        7.14312121e-02, -5.83239980e-02,  4.58900351e-03,  1.56194316e-02,
        1.03841480e-02, -4.26567495e-02,  1.35176834e-02, -5.60860261e-02,
        1.86445098e-02, -1.47688454e-02, -4.86133806e-02, -1.01973033e-02,
        6.46221414e-02,  1.17162736e-02,  4.91274819e-02, -4.35938798e-02,
       -2.97329854e-02, -5.42693250e-02,  3.84951942e-02,  1.90193243e-02,
        6.83268085e-02, -4.08832841e-02,  4.66427803e-02,  3.03016999e-03,
       -1.16352178e-02, -5.24238124e-02, -3.03320941e-02,  2.34115515e-02,
        2.92663765e-03,  9.56124663e-02, -4.42394018e-02,  5.22620697e-03],
      dtype=float32)

In [151]:
embeddings[:16]

array([-0.13156408, -0.00678268, -0.00367609,  0.03265162,  0.11219638,
        0.01227266,  0.09816723, -0.09005228,  0.04231165, -0.0197735 ,
       -0.03308417,  0.07452939,  0.10632038, -0.0206043 , -0.02052102,
        0.00169492], dtype=float32)

In [152]:
# top 5 lekar usko list meh convert kar diya
sample_embedding=model.encode(df["paper_text"].head(5).to_list())
sample_embedding

array([[-0.13156408, -0.00678267, -0.00367612, ...,  0.09561247,
        -0.04423936,  0.00522619],
       [-0.03589674, -0.06343269, -0.00394962, ...,  0.07206136,
        -0.13262011, -0.00412081],
       [-0.08129282,  0.02410301, -0.0886826 , ..., -0.04524422,
        -0.04765854, -0.01549939],
       [-0.10218995, -0.06282566,  0.03273677, ..., -0.03118814,
         0.03174182,  0.03621244],
       [-0.08391044,  0.01838461, -0.01556659, ..., -0.01188401,
        -0.10644458,  0.00790993]], dtype=float32)

In [153]:
print(sample_embedding.shape)

(5, 384)

## 3. Cosine Similarity
This subsection demonstrates how cosine similarity can be used to measure the similarity between two embeddings. A higher cosine similarity score indicates greater semantic resemblance.

## Insights
5 --> because we took head(5)

In [154]:
from sklearn.metrics.pairwise import cosine_similarity

In [155]:
# Cosine similarity expects 2D
# Here reshape(1,-1) --> take 1 row and adjust the columns to the remaining ones
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
similarity

array([[1.]], dtype=float32)

In [156]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
similarity

array([[0.36625272]], dtype=float32)

In [157]:
# Calculating similarity for first 5
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[0.36625272]]
[[0.3352284]]
[[0.15505117]]
[[0.37421536]]

## Insights
4th wala paper is most similar to the 1st paper

## Generate full embedding for 15000

## 4. FAISS Indexing for Efficient Search
This section uses the FAISS (Facebook AI Similarity Search) library to create an efficient index for the entire dataset's embeddings. This allows for fast similarity searches, which is crucial for large datasets. The embeddings and the FAISS index are saved to disk for persistence, avoiding regeneration on subsequent runs.

In [158]:
# batch_size is used so that we don't do embedding all at once nd break them into batches and then do the embedding
# This method is used so that all RAM does not eats up
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings

In [159]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)
    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index

FAISS --> It creates a special search structure

Cosine Similarity --> dot product hota hai

FAISS --> Inner product hota hai

L2 Normalization

In [160]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [161]:
import faiss

In [162]:
# Normalise embedding
# faiss.normalize_L2(embedding)

In [163]:
# Create index
# Here IP means Inner Product it means it creates inner product for all embeddings
# index=faiss.IndexFlatIP(384)
# index

In [164]:
# Add the L2 normalized embeddings to the FAISS index.
# This prepares the index for efficient similarity searches.
# index.add(embedding)

In [165]:
# print(index.ntotal)

In [166]:
# Create embedding for a query
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
print(query_embedding.shape)

(1, 384)

In [167]:
# Normalize the query_embedding
faiss.normalize_L2(query_embedding)

In [168]:
# To search how closely our query matches with the stored vectors of the research papers
D,I=index.search(query_embedding,5)
print(D) # Similarity Score --> tells us the similarity score between our query nd the reseach papers stored in the FAISS
print(I) # Indices --> It tells konse paper no seh it is similar

[[0.6807246  0.67092216 0.6521999  0.62811756 0.6131154 ]]
[[10466 13730 11873 12691 11282]]

Here, we display the top matching research papers found by the FAISS index based on the query. We show the similarity score, title, and the beginning of the abstract for each paper.

In [169]:
print(df.iloc[10466 ]["title"])

A Perspective on Deep Imaging

In [170]:
print(df.iloc[10466 ]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [171]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

In [179]:
def search_paper(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        print("Similarity Score:", score)
        print("Title:", df.iloc[idx]["title"])
        print("Abstract:", df.iloc[idx]["abstract"][:500])
        print()

In [181]:
search_paper("deep learning for medical image analysis")

Similarity Score: 0.6807246
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Similarity Score: 0.67092216
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

Similarity Score: 0.6521999
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

Similarity Score: 0.62811756
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

Similarity Score: 0.6131154
Title: Deep Learning for the Classification of Lung Nodules
Abstract:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

In [173]:
!pip install transformers==4.46.3

Requirement already satisfied: transformers==4.46.3 in /usr/local/lib/python3.12/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.5.20)

## 5. Abstract Summarization with Hugging Face Transformers
This section integrates a pre-trained summarization model from the Hugging Face Transformers library to generate concise summaries of the retrieved paper abstracts. This enhances the utility of the search by providing quick overviews of relevant papers.

In [175]:
from transformers import pipeline
summarizer=pipeline(
    task="summarization",
    model="facebook/bart-large-cnn",
    device=0
)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [176]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

This helper function `search_paper` encapsulates the entire search logic: encoding the query, normalizing it, performing the FAISS search, and then printing the detailed results including similarity scores, titles, and truncated abstracts.

In [182]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [183]:
type(summary)

list

In [185]:
type(summary[0])

dict

In [186]:
type(summary[0]["summary_text"])

str

In [187]:
print(summary[0]["summary_text"])

The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

In [190]:
for score, idx in zip(D[0], I[0]):
    print("Similarity Score:", score)
    print("Title:", df.iloc[idx]["title"])
    print("Abstract:", df.iloc[idx]["abstract"][:500])

    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
    print(summary)
    print(summary[0]["summary_text"])
    print()

Similarity Score: 0.6807246
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity Score: 0.67092216
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
[{'summary_text': 'Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.'}]
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Similarity Score: 0.6521999
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
[{'summary_text': 'The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.'}]
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Similarity Score: 0.62811756
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
[{'summary_text': 'The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.'}]
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Similarity Score: 0.6131154
Title: Deep Learning for the Classification of Lung Nodules
Abstract:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
[{'summary_text': 'Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.'}]
Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.

This final loop combines the FAISS search results with the summarization pipeline. For each top matching paper, it not only displays the similarity score, title, and abstract but also generates and prints a concise summary of the abstract using the `summarizer`.